# Practice-06 - Runner Context
name: PR-06 - Context
on: 
  push:
    branches: ["main"]

jobs:
  runner-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Information about the runner (os)
        run: |
          echo "Runner OS: ${{ runner.os }}"
      - name: Information about the runner (architecture)
        run: |
          echo "Runner architecture: ${{ runner.arch }}"